/* Auto-generated by gen_soc_test.py — do not edit */
#ifndef SOC_TEST_DATA_H
#define SOC_TEST_DATA_H
#include <stdint.h>

/* Model: model_d_int8 */
#define BLOB_MODEL_BASE  0x40010000
#define BLOB_MODEL_SIZE  2450396

/* Per-layer blob entry header (36 uint32 words = 144 bytes) */
typedef struct {
    uint32_t n_wgt;            /* [0]  */
    uint32_t n_param;          /* [1]  */
    uint32_t n_input;          /* [2]  */
    uint32_t n_output;         /* [3]  */
    uint32_t op_type;          /* [4]  */
    uint32_t data_type;        /* [5]  */
    uint32_t in_hw;            /* [6]  */
    uint32_t in_c;             /* [7]  */
    uint32_t out_hw;           /* [8]  */
    uint32_t out_c;            /* [9]  */
    uint32_t kernel_dil;       /* [10] */
    uint32_t stride;           /* [11] */
    uint32_t padding;          /* [12] */
    uint32_t post_ctrl;        /* [13] */
    uint32_t param_count;      /* [14] */
    uint32_t dma_in_size;      /* [15] */
    uint32_t dma_wgt_size;     /* [16] */
    uint32_t dma_out_size;     /* [17] */
    uint32_t cfg_aux;          /* [18] */
    uint32_t tile_cfg;         /* [19] */
    uint32_t tile_count;       /* [20] */
    uint32_t sched_ctrl;       /* [21] */
    uint32_t store_mode;       /* [22] */
    uint32_t tile_in_size;     /* [23] */
    uint32_t tile_out_size;    /* [24] */
    uint32_t row_cfg;          /* [25] */
    uint32_t wgt_per_oc_words; /* [26] */
    uint32_t clamp_max;        /* [27] */
    uint32_t in_zp;            /* [28] */
    uint32_t ddr_wgt_addr;     /* [29] */
    uint32_t ddr_param_addr;   /* [30] */
    uint32_t ddr_out_addr;     /* [31] */
    uint32_t ddr_in_addr;      /* [32] */
    uint32_t ddr_add_b_addr;   /* [33] */
    int32_t  input_src;        /* [34] -1=chain, N=skip */
    int32_t  residual_src;     /* [35] -1=none, N=branch B */
} __attribute__((packed)) layer_entry_t;

#define LAYER_ENTRY_HDR_SIZE  144
#define LAYER_ENTRY_HDR_WORDS 36

/* Blob header */
#define BLOB_MAGIC 0x4E505532
#define BLOB_OFF_MAGIC   0
#define BLOB_OFF_LAYERS  4
#define BLOB_OFF_VERSION 8
#define BLOB_OFF_DATA    12

#endif /* SOC_TEST_DATA_H */
